// Generated by Selenium IDE
package selenium11;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC1() {
    // Test name: TC1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.youtube.com/");
    // 2 | setWindowSize | 1199x680 | 
    driver.manage().window().setSize(new Dimension(1199, 680));
    // 3 | click | name=search_query | 
    driver.findElement(By.name("search_query")).click();
    // 4 | runScript | window.scrollTo(0,448.6666564941406) | 
    js.executeScript("window.scrollTo(0,448.6666564941406)");
    // 5 | runScript | window.scrollTo(0,1085.3333740234375) | 
    js.executeScript("window.scrollTo(0,1085.3333740234375)");
    // 6 | runScript | window.scrollTo(0,1526) | 
    js.executeScript("window.scrollTo(0,1526)");
    // 7 | click | name=search_query | 
    driver.findElement(By.name("search_query")).click();
    // 8 | doubleClick | name=search_query | 
    {
      WebElement element = driver.findElement(By.name("search_query"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 9 | doubleClick | name=search_query | 
    {
      WebElement element = driver.findElement(By.name("search_query"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 10 | click | name=search_query | 
    driver.findElement(By.name("search_query")).click();
    // 11 | click | name=search_query | 
    driver.findElement(By.name("search_query")).click();
    // 12 | type | name=search_query | spring boot monolithic 
    driver.findElement(By.name("search_query")).sendKeys("spring boot monolithic ");
    // 13 | sendKeys | name=search_query | ${KEY_DOWN}
    driver.findElement(By.name("search_query")).sendKeys(Keys.DOWN);
    // 14 | sendKeys | name=search_query | ${KEY_ENTER}
    driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
    // 15 | runScript | window.scrollTo(0,614) | 
    js.executeScript("window.scrollTo(0,614)");
    // 16 | runScript | window.scrollTo(0,270.6666564941406) | 
    js.executeScript("window.scrollTo(0,270.6666564941406)");
    // 17 | runScript | window.scrollTo(0,483.3333435058594) | 
    js.executeScript("window.scrollTo(0,483.3333435058594)");
    // 18 | runScript | window.scrollTo(0,1313.3333740234375) | 
    js.executeScript("window.scrollTo(0,1313.3333740234375)");
    // 19 | runScript | window.scrollTo(0,1426) | 
    js.executeScript("window.scrollTo(0,1426)");
    // 20 | runScript | window.scrollTo(0,1600.6666259765625) | 
    js.executeScript("window.scrollTo(0,1600.6666259765625)");
    // 21 | runScript | window.scrollTo(0,2018.6666259765625) | 
    js.executeScript("window.scrollTo(0,2018.6666259765625)");
    // 22 | runScript | window.scrollTo(0,2334.666748046875) | 
    js.executeScript("window.scrollTo(0,2334.666748046875)");
    // 23 | runScript | window.scrollTo(0,3071.333251953125) | 
    js.executeScript("window.scrollTo(0,3071.333251953125)");
    // 24 | runScript | window.scrollTo(0,4018) | 
    js.executeScript("window.scrollTo(0,4018)");
    // 25 | mouseOver | linkText=Spring Framework and Microservices Full Course | 
    {
      WebElement element = driver.findElement(By.linkText("Spring Framework and Microservices Full Course"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 26 | mouseOut | linkText=Spring Framework and Microservices Full Course | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 27 | click | css=.style-scope:nth-child(2) > #dismissible .yt-core-image | 
    driver.findElement(By.cssSelector(".style-scope:nth-child(2) > #dismissible .yt-core-image")).click();
    // 28 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 29 | runScript | window.scrollTo(0,78.66666412353516) | 
    js.executeScript("window.scrollTo(0,78.66666412353516)");
    // 30 | mouseOver | css=.ytp-autonav-toggle-button-container | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytp-autonav-toggle-button-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 31 | mouseOut | css=.ytp-autonav-toggle-button-container | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 32 | mouseOver | id=logo-icon | 
    {
      WebElement element = driver.findElement(By.id("logo-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 33 | mouseOut | id=logo-icon | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 34 | mouseOver | css=#logo > #logo .ytd-topbar-logo-renderer > #logo-icon div | 
    {
      WebElement element = driver.findElement(By.cssSelector("#logo > #logo .ytd-topbar-logo-renderer > #logo-icon div"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 35 | mouseOut | css=#logo > #logo .ytd-topbar-logo-renderer > #logo-icon div | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 36 | runScript | window.scrollTo(0,4129.91650390625) | 
    js.executeScript("window.scrollTo(0,4129.91650390625)");
    // 37 | type | name=search_query | spring boot
    driver.findElement(By.name("search_query")).sendKeys("spring boot");
    // 38 | sendKeys | name=search_query | ${KEY_ENTER}
    driver.findElement(By.name("search_query")).sendKeys(Keys.ENTER);
    // 39 | mouseOver | css=.ytd-item-section-renderer:nth-child(2) > #dismissible .yt-core-image | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(2) > #dismissible .yt-core-image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 40 | mouseOut | css=.ytd-item-section-renderer:nth-child(2) > #dismissible .yt-core-image | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 41 | mouseOver | css=.ytd-item-section-renderer:nth-child(2) > #dismissible #video-title > .style-scope:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.cssSelector(".ytd-item-section-renderer:nth-child(2) > #dismissible #video-title > .style-scope:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 42 | mouseOut | css=.ytd-item-section-renderer:nth-child(2) > #dismissible #video-title > .style-scope:nth-child(2) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
